version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "32001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=colegio
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  usuarios:
    image: sebasbelmos/usuarios:latest
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  notas:
    image: sebasbelmos/notas:latest
    networks:
      - app-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  web:
    image: sebasbelmos/web:latest
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
