version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32001:3306"  # Cambiado de 32000 a 32001
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=colegio
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  usuarios:
    build: ./appColegio/microUsuarios
    container_name: usuarios
    ports:
      - "3021:3001"  # Cambiado de 3001 a 3021
    depends_on:
      - db
    networks:
      - app-network

  notas:
    build: ./appColegio/microNotas
    container_name: notas
    ports:
      - "3022:3002"  # Cambiado de 3002 a 3022
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./APPWEB
    container_name: web
    ports:
      - "8090:80"  # Cambiado de 8080 a 8090
    depends_on:
      - usuarios
      - notas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
