services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32000:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=colegio
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  usuarios:
    build: ./appColegio/microUsuarios
    container_name: usuarios
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network

  notas:
    build: ./appColegio/microNotas
    container_name: notas
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./APPWEB
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - usuarios
      - notas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
