version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "32001:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=colegio
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  usuarios:
    build: ./appColegio/microUsuarios
    container_name: usuarios
    ports:
      - "3030:3030"
    depends_on:
      - db
    networks:
      - app-network

  notas:
    build: ./appColegio/microNotas
    container_name: notas
    ports:
      - "3031:3031" 
    depends_on:
      - db
    networks:
      - app-network

  web:
    build: ./APPWEB
    container_name: web
    ports:
      - "8090:80"  
    depends_on:
      - usuarios
      - notas
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
